language: rust
cache: cargo

# Can't use stable/beta until try_from is stabilized
matrix:
  include:
  # compiletest_rs & clippy only work on nightly
  - rust: nightly
    script:
    - cargo test --all --features "compiletest clippy" --verbose
