language: rust
cache: cargo

rust:
- stable
- beta
matrix:
  include:
  # compiletest_rs & clippy only work on nightly
  - rust: nightly
    script:
    - cargo test --features "compiletest clippy" --verbose
