language: rust
# Can't use cache due to compiletest-rs#101

# Can't use stable/beta until try_from is stabilized
matrix:
  include:
  - rust: nightly
    script:
    - cargo test --all --verbose
  - rust: nightly
    script:
    - cargo test --all --verbose --no-default-features
  # clippy only works on nightly
  - rust: nightly
    install:
    - cargo install --force clippy
    script:
    - cargo clippy --all --verbose
