language: rust
cache: cargo

# Can't use stable/beta until try_from is stabilized
matrix:
  include:
  - rust: nightly
    script:
    - cargo test --all --verbose
  # clippy only works on nightly
  - rust: nightly
    install:
    - cargo install clippy
    script:
    - cargo clippy --all --verbose
